services:

  db:
    image: postgres
    container_name: task_tracker_postgres_db
    restart: always
    networks:
      - db_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: task_tracker_adminer
    restart: always
    networks:
      - db_net
    ports:
      - 8080:8080

  web:
    build: .
    container_name: task_tracker_web
    restart: always
    networks:
      - db_net
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    image: task_tracker


volumes:
  postgres_data:

networks:
  db_net:
    driver: bridge